# Generated by Django 5.2.1 on 2025-05-31 11:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def update_search_vector(apps, schema_editor):
    Course = apps.get_model("core", "Course")
    Course.objects.update(
        search_vector=django.contrib.postgres.search.SearchVector("title", weight="A")
        + django.contrib.postgres.search.SearchVector("description", weight="B")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="course",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="course_search_idx"
            ),
        ),
        migrations.RunPython(update_search_vector),
    ]
